<Project>
  <PropertyGroup>
    <Version Condition="'$(Version)' == ''">0.2.0</Version>
    <VersionCore>$([System.Text.RegularExpressions.Regex]::Match('$(Version)', '^\d+\.\d+\.\d+').Value)</VersionCore>
    <InstallerVersion Condition="'$(VersionCore)' != ''">$(VersionCore)</InstallerVersion>
    <MSIXPackageVersion Condition="'$(InstallerVersion)' != ''">$(InstallerVersion).0</MSIXPackageVersion>
    <MSIXPackageIdentityName Condition="'$(MSIXPackageIdentityName)' == '' and '$(MS_STORE_PACKAGE_IDENTITY_NAME)' != ''">$(MS_STORE_PACKAGE_IDENTITY_NAME)</MSIXPackageIdentityName>
    <MSIXPackageIdentityName Condition="'$(MSIXPackageIdentityName)' == ''">SnapView</MSIXPackageIdentityName>
    <MSIXPackagePublisher Condition="'$(MSIXPackagePublisher)' == '' and '$(MS_STORE_PACKAGE_PUBLISHER)' != ''">$(MS_STORE_PACKAGE_PUBLISHER)</MSIXPackagePublisher>
    <MSIXPackagePublisher Condition="'$(MSIXPackagePublisher)' == ''">CN=BurnettSoft</MSIXPackagePublisher>
    <MSIXPackagePublisherDisplayName Condition="'$(MSIXPackagePublisherDisplayName)' == '' and '$(MS_STORE_PACKAGE_PUBLISHERDISPLAYNAME)' != ''">$(MS_STORE_PACKAGE_PUBLISHERDISPLAYNAME)</MSIXPackagePublisherDisplayName>
    <MSIXPackagePublisherDisplayName Condition="'$(MSIXPackagePublisherDisplayName)' == ''">Brant Burnett</MSIXPackagePublisherDisplayName>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts\</ArtifactsPath>
    <ArtifactConfiguration>$([System.String]::Copy('$(Configuration)').ToLowerInvariant())</ArtifactConfiguration>
    <ArtifactPlatform>$([System.String]::Copy('$(Platform)').ToLowerInvariant())</ArtifactPlatform>
    <ArtifactConfigurationPlatform>$(ArtifactConfiguration)-$(ArtifactPlatform)</ArtifactConfigurationPlatform>
    <BaseOutputPath>$(ArtifactsPath)bin\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(ArtifactsPath)obj\$(MSBuildProjectName)\$(ArtifactConfigurationPlatform)\</BaseIntermediateOutputPath>
    <ArtifactsBinPath>$(ArtifactsPath)bin\$(MSBuildProjectName)\$(ArtifactConfigurationPlatform)\</ArtifactsBinPath>
    <ArtifactsObjPath>$(ArtifactsPath)obj\$(MSBuildProjectName)\$(ArtifactConfigurationPlatform)\</ArtifactsObjPath>
    <ArtifactsPublishPath>$(ArtifactsPath)publish\$(ArtifactConfiguration)\</ArtifactsPublishPath>
  </PropertyGroup>
</Project>
